# Generated by Django 4.2 on 2023-05-09 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0001_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='car_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.carbrand'),
        ),
        migrations.AddField(
            model_name='car',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.agency'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.carmodel'),
        ),
        migrations.AddField(
            model_name='agency',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.city'),
        ),
    ]
